"""Initial migration

Revision ID: f03af72c2b09
Revises: 
Create Date: 2024-04-25 20:51:12.275282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03af72c2b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('every_year', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_name'), 'action', ['name'], unique=False)
    op.create_table('activity_code',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_code_name'), 'activity_code', ['name'], unique=False)
    op.create_table('contact',
    sa.Column('fullname', sa.String(length=150), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', name='contact_level'), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=False),
    sa.Column('profession', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_fullname'), 'contact', ['fullname'], unique=False)
    op.create_index(op.f('ix_contact_profession'), 'contact', ['profession'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_profession'), table_name='contact')
    op.drop_index(op.f('ix_contact_fullname'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_activity_code_name'), table_name='activity_code')
    op.drop_table('activity_code')
    op.drop_index(op.f('ix_action_name'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
